default_language_version:
    python: python3.8
exclude: ^\..*
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort
      # https://pycqa.github.io/isort/docs/configuration/options/
      args: [
        --multi-line=3,
        --profile=black,
      ]
      files: ^.*\.py$
  - repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
    - id: black
      files: ^.*\.py$
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
      # https://flake8.pycqa.org/en/latest/user/options.html
      # https://flake8.pycqa.org/en/latest/user/error-codes.html  
      args: [
        --max-doc-length=88,
        --max-line-length=88,
      ]
      files: ^.*\.py$
#  - repo: https://github.com/python/mypy
#    rev: v0.812
#    hooks:
#    - id: mypy
#      # https://mypy.readthedocs.io/en/stable/command_line.html
#      args: [
#        --cache-dir=/dev/null,
#      ]
#      files: ^.*\.py$
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0
    hooks:
    - id: pydocstyle
      # http://www.pydocstyle.org/en/stable/usage.html
      args: [
        --convention=numpy,
      ]
      files: ^.*\.py$
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.5
    hooks:
    - id: mdformat
      args: [
        --wrap=88,
      ]
      files: ^.*\.md$
