name: Render and bundle docs

on:
  push:
    branches:
      - new-rendering-script

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout https://github.com/carnarez/astdocs repository
        uses: actions/checkout@v3

      - name: Set up Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Node dependencies
        run: |
          npm install --global --no-audit --no-fund \
            autoprefixer \
            clean-css-cli \
            html-minifier \
            postcss-cli \
            terser

      - name: Set up Python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir \
            ghp-import \
            git+https://github.com/carnarez/astdocs@master \
            git+https://github.com/carnarez/markdown-astdocs@master \
            git+https://github.com/carnarez/markdown-img@master \
            git+https://github.com/carnarez/markdown-insert@master \
            git+https://github.com/carnarez/markdown-script@master \
            jinja2 \
            lunr \
            markdown \
            pymdown-extensions \
            pyyaml

      - name: Render and bundle
        run: |
          # generate the documentation
          (
            cd astdocs
            astdocs astdocs.py > ../web/index.md
          )
          # render the documentation
          (
            cd web
            # will contain all rendered/bundled content
            mkdir www
            # download the stylesheets
            wget --directory-prefix=www https://raw.githubusercontent.com/carnarez/markdown-tests/master/static/style.css
            wget --directory-prefix=www https://raw.githubusercontent.com/carnarez/markdown-tests/master/static/style-highlight.css
            wget --directory-prefix=www https://raw.githubusercontent.com/carnarez/markdown-tests/master/static/style-markdown.css
            wget --directory-prefix=www https://raw.githubusercontent.com/carnarez/markdown-tests/master/static/style-mermaid.css
            # convert markdown to html
            wget https://raw.githubusercontent.com/carnarez/markdown-tests/master/build/render.py
            wget https://raw.githubusercontent.com/carnarez/markdown-tests/master/build/template.html
            echo "[TOC]" | cat front-matter.md - index.md > tmp
            mv tmp index.md
            python render.py --prefix=www --root=https://carnarez.github.io/astdocs/ index.md
            # bundle css
            find www -name "*.css" | while read f; do
              postcss $f --replace --use autoprefixer
              cleancss --output $f $f
            done
            # bundle html
            find www -name "*.html" | while read f; do
              html-minifier --collapse-boolean-attributes \
                            --collapse-whitespace \
                            --output $f \
                            --minify-css true \
                            --minify-js true \
                            --remove-attribute-quotes \
                            --remove-comments \
                            --remove-empty-attributes \
                            --remove-optional-tags \
                            --remove-redundant-attributes \
                            --remove-script-type-attributes \
                            --remove-style-link-type-attributes \
                            --use-short-doctype \
                            $f
            done
            # bundle javascript
            find . -name "*.js" | while read f; do
              terser --compress --mangle --output $f $f
            done
          )

      - name: Deploy to https://carnarez.github.io/astdocs/
        run: |
          (
            cd web
            ghp-import --branch www --force --no-jekyll --push www
          )
