name: Run Python tests

on:
  push:
    path:
      - '**.py'

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout https://github.com/carnarez/astdocs repository
        uses: actions/checkout@v2

      - name: Set up Python v3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir pytest pytest-cov

      - name: Run pytest
        run: |
          python -m pytest --color=yes --cov=naiad --cov-report term-missing --verbose
